spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/purchase_db
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
server:
  port: 8099
app:
  openapi:
    server-url: http://localhost:8099
    server-description: Development Server
  cors:
    allowed-origins:
      - http://localhost:4200
  jwt:
    secret: bXlTdXBlclNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvblRoYXRJc0F0TGVhc3QyNTZCaXRzTG9uZzEyMzQ1Njc4OTA=
    expiration: 86400000
    refresh-expiration: 604800000
  mail:
    enabled: true
    from: noreply@prpo-system.com
logging:
  level:
    com.jirapat.prpo.api: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
